#!/usr/local/bin/zsh

# export data from odbc source using sql file to .txt file
function isql-export-to-text () {
  if [ "$#" -ne 3 ]; then
    echo "Illegal number of parameters";
    echo "Should be export_isql odbc_dsn_name sql_file text_file";
    return 1;
  fi;
  replace-newlines-with-spaces $2;
  isql -v -b -3 -d"|" $1 < $2 > $3;
}
