#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..


if test ! "$(uname)" = "Darwin"
  then
  find . -not -path './macos/*' -name install.sh | while read installer ; do sh -c "${installer}" ; done
  else
  find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
fi
