#!/usr/bin/env bash
#
# Run all dotfiles installers.

# Ask for the administrator password upfront
sudo -v

set -e

cd "$(dirname $0)"/..


if test ! "$(uname)" = "Darwin"
  then
    echo "Running install.sh except ./macos/*"
    find . -not -path './macos/*' -name install.sh | while read installer ; do
      echo "${installer}"
      sh -c "${installer}" ;
      done
  else
    echo "Running install.sh including ./macos/*"
    find . -name install.sh | while read installer ; do
      echo "${installer}"
      sh -c "${installer}" ;
      done
fi
